[build]
  command = "npm run shared:build && npm run admin:build"
  publish = "web-admin/.next"

[env.production]
  BACKEND_URL = "https://api.parivaarapp.in"

[env.preview]
  BACKEND_URL = "https://api.parivaarapp.in"

[env.development]
  BACKEND_URL = "https://api.parivaarapp.in"
