[build]
  command = "npm run shared:build && npm run admin:build"
  publish = "web-admin/.next"

[env.production]
  BACKEND_URL = "http://api.parivaarapp.in:3002"

[env.preview]
  BACKEND_URL = "http://api.parivaarapp.in:3002"

[env.development]
  BACKEND_URL = "http://api.parivaarapp.in:3002"
