/**
 * Search synonyms per business category id. Includes English, common Hinglish,
 * and service words members actually type ("kapda", "gaadi", "doctor", "CA").
 * Keys must match ids in BusinessTypes (including subTypes).
 */
export const BusinessCategorySynonyms: Record<string, string[]> = {
  HomeMaker: ['homemaker', 'housewife', 'home maker', 'grihini'],
  SelfEmployed: ['self employed', 'freelance', 'freelancer', 'consultant', 'independent'],
  Automobile: ['car', 'cars', 'bike', 'vehicle', 'gaadi', 'gadi', 'auto', 'garage', 'mechanic', 'showroom', 'two wheeler', 'four wheeler', 'spare parts', 'tyre', 'tyres'],
  Advertising: ['ads', 'advertisement', 'marketing', 'branding', 'hoarding', 'printing', 'flex', 'banner', 'digital marketing', 'social media'],
  Agriculture: ['farm', 'farming', 'kheti', 'kisan', 'crop', 'seeds', 'fertilizer', 'agri', 'khad', 'beej'],
  ClothMerchant: ['cloth', 'clothes', 'clothing', 'kapda', 'kapde', 'garments', 'textile', 'fabric', 'saree', 'sari', 'suit', 'dress', 'apparel', 'fashion', 'boutique', 'readymade', 'kurti', 'lehenga'],
  ConstructionMaterials: ['construction', 'building material', 'cement', 'sand', 'bricks', 'eent', 'ret', 'bajri', 'gitti', 'tmt', 'steel bar', 'contractor', 'builder'],
  EducationInstitutions: ['school', 'college', 'coaching', 'tuition', 'institute', 'academy', 'classes', 'teacher', 'education', 'padhai', 'training'],
  Electricals: ['electrical', 'electrician', 'wiring', 'wire', 'switch', 'fan', 'light', 'bijli', 'motor', 'inverter', 'battery'],
  HomeAppliances: ['electronics', 'appliances', 'tv', 'television', 'fridge', 'refrigerator', 'ac', 'air conditioner', 'washing machine', 'cooler', 'mobile', 'phone', 'gadget'],
  Computers: ['computer', 'laptop', 'it', 'software', 'hardware', 'printer', 'repair', 'website', 'web', 'app', 'developer', 'programmer', 'tech', 'technology'],
  FinancialAdvisor: ['finance', 'financial', 'investment', 'mutual fund', 'insurance', 'lic', 'loan', 'sip', 'stock', 'share market', 'wealth', 'advisor', 'planner', 'bima'],
  GeneralStore: ['general store', 'kirana', 'grocery', 'groceries', 'provision', 'ration', 'daily needs', 'supermarket', 'mart', 'dukan', 'shop'],
  Glass: ['glass', 'hardware', 'mirror', 'aluminium', 'aluminum', 'sheesha', 'window', 'door', 'fitting'],
  HomeDecor: ['home decor', 'decor', 'furnishing', 'furniture', 'interior', 'curtain', 'parda', 'sofa', 'mattress', 'gadda', 'carpet', 'lighting', 'designer'],
  Hospitals: ['hospital', 'clinic', 'doctor', 'dr', 'medical', 'medicine', 'pharmacy', 'chemist', 'dawai', 'dawa', 'nursing', 'lab', 'pathology', 'dentist', 'physician', 'health'],
  'Hotels&Restaurants': ['hotel', 'restaurant', 'food', 'khana', 'dhaba', 'cafe', 'bakery', 'sweets', 'mithai', 'catering', 'caterer', 'tiffin', 'dining', 'eatery', 'lodge', 'stay'],
  IronSteel: ['iron', 'steel', 'loha', 'metal', 'trader', 'angle', 'channel', 'pipe', 'fabrication', 'welding'],
  Jwellery: ['jewellery', 'jewelry', 'jeweller', 'gold', 'silver', 'sona', 'chandi', 'diamond', 'ornaments', 'gehne', 'zewar', 'bangles', 'ring'],
  Manufacturing: ['manufacturing', 'manufacturer', 'factory', 'industry', 'industries', 'production', 'unit', 'plant', 'karkhana'],
  Laminates: ['ply', 'plywood', 'laminate', 'laminates', 'board', 'veneer', 'sunmica', 'mdf', 'timber', 'lakdi', 'wood'],
  Marble: ['marble', 'granite', 'tiles', 'stone', 'pathar', 'flooring', 'kota', 'sandstone', 'slab'],
  Professionals: ['professional', 'expert', 'specialist'],
  Engineer: ['engineer', 'engineering', 'civil', 'mechanical', 'electrical engineer', 'site engineer', 'software engineer'],
  CA: ['ca', 'chartered accountant', 'accountant', 'accounts', 'tax', 'gst', 'itr', 'income tax', 'audit', 'auditor', 'cs', 'company secretary'],
  Doctor: ['doctor', 'dr', 'physician', 'surgeon', 'mbbs', 'md', 'specialist', 'dentist', 'clinic'],
  Architect: ['architect', 'architecture', 'design', 'naksha', 'plan', 'interior designer', 'civil'],
  Lawyer: ['lawyer', 'advocate', 'vakil', 'legal', 'court', 'attorney', 'barrister', 'solicitor', 'legal advisor', 'vkeel'],
  MBA: ['mba', 'manager', 'management', 'consultant', 'business analyst', 'corporate'],
  RealEstate: ['real estate', 'property', 'plot', 'flat', 'house', 'makaan', 'zameen', 'land', 'broker', 'dealer', 'rent', 'lease', 'builder', 'apartment'],
  Service: ['service', 'services', 'repair', 'maintenance', 'agency', 'support'],
  Stationary: ['stationery', 'stationary', 'books', 'kitab', 'copy', 'pen', 'paper', 'xerox', 'photocopy', 'printing', 'office supplies'],
  Machineries: ['machine', 'machinery', 'machines', 'equipment', 'tools', 'pump', 'generator', 'compressor', 'industrial'],
  TourTravels: ['tour', 'travel', 'travels', 'trip', 'yatra', 'ticket', 'flight', 'bus', 'taxi', 'cab', 'holiday', 'package', 'visa', 'passport', 'tourism'],
  WeddingEventManagement: ['wedding', 'shaadi', 'shadi', 'event', 'events', 'decoration', 'decorator', 'tent', 'band', 'dj', 'planner', 'mandap', 'party', 'catering', 'photography', 'photographer'],
  Beautician: ['beauty', 'beautician', 'salon', 'saloon', 'parlour', 'parlor', 'makeup', 'bridal', 'hair', 'spa', 'mehndi', 'mehandi', 'nails', 'grooming'],
  Hardware: ['hardware', 'tools', 'nuts', 'bolts', 'paint', 'plumbing', 'sanitary', 'tap', 'pipe', 'fittings', 'lock', 'tala'],
  Paints: ['paint', 'paints', 'painter', 'painting', 'rang', 'colour', 'color', 'asian paints', 'putty', 'polish', 'primer'],
  Footwear: ['footwear', 'shoes', 'shoe', 'chappal', 'sandal', 'sandals', 'juta', 'jute', 'slippers', 'boots', 'sneakers'],
  Transport: ['transport', 'transporter', 'logistics', 'truck', 'tempo', 'cargo', 'courier', 'delivery', 'goods', 'shifting', 'packers', 'movers', 'freight'],
  Utensils: ['utensils', 'bartan', 'steel utensils', 'crockery', 'kitchenware', 'cookware', 'pressure cooker', 'thali', 'bhandi', 'bhande'],
  Turf: ['turf', 'ground', 'cricket', 'football', 'box cricket', 'playground', 'arena', 'court'],
  Sports: ['sports', 'sport', 'gym', 'fitness', 'yoga', 'coaching', 'cricket', 'badminton', 'equipment', 'academy'],
  Others: [],
};
